### ISSUE TITLE
URLs entered without "http://" don't work

### ISSUE THREAD

**Issue by ed-parry** [tdkeepings/Dashboard#2]
If a user enters a URL without "http://" at the beginning, it fails to open the link correctly from the list view. Poss fix to include a drop-down of "http://", "https://" at the beginning to always include by default.

**Comment by tdkeepings** [comment]
Took me long enough but I've added a potential fix for this :) Not as graceful as adding something to the front end but it'll do. Just need to build it and release it up from my machine back home!
